

apiVersion: v1
kind: Namespace
metadata:
  name: rootsmarket
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    app.kubernetes.io/part-of: rootsmarket
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    pod-security.kubernetes.io/enforce: privileged
    app.kubernetes.io/part-of: rootsmarket