
apiVersion: v1
kind: Secret
metadata:
  name: rootsmarket-secrets
  namespace: rootsmarket
  labels:
    app.kubernetes.io/part-of: rootsmarket
type: Opaque
stringData:
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  RABBITMQ_USER: ""
  RABBITMQ_PASSWORD: ""

  RABBITMQ_URL: "amqp://admin:admin@rabbitmq.rootsmarket.svc.cluster.local:5672"